### ISSUE TITLE
TS6 spec requires BMASK to be used for banlike modes rather than TMODE

### ISSUE THREAD

**Issue by cooper** [GLolol/PyLink#248]

**Comment by GLolol** [comment]
Actually, the mode bursting stuff in relay and all the protocol modules should use a checkup. I don't remember off the top of my head which IRCds allow plain bans in SJOIN, and which use separate commands...

**Comment by kaniini** [comment]
Only unreal allows bans in SJOIN.

**Comment by GLolol** [comment]
I've investigated this a little bit more and it seems that one cause of the issue might be different handling of ban bursting on different IRCds. InspIRCd, for example, bursts bans after the SJOIN as a regular MODE, meaning that when the initial SJOIN is forwarded, no bans are set yet. The second MODE command that bursts the ban is then interpreted as a regular MODE, because PyLink can't tell for sure whether it's part of a burst or not.

**Comment by GLolol** [comment]
Fixed in devel for the next release.
